CREATE TABLE ROLE(
ROLE_ID Numeric(10,0)  CONSTRAINT NN_ROLE_ID NOT NULL,
ROLE_NAME VARCHAR(50) CONSTRAINT NN_ROLE_NAME NOT NULL,
CONSTRAINT ROLE_PK PRIMARY KEY(ROLE_ID)
);
COMMENT ON COLUMN ROLE.ROLE_ID IS 'Unique ID Role';
COMMENT ON COLUMN ROLE.ROLE_NAME IS 'Name Role';

----INSERT INTO role VALUES (1,'ADMIN');