ALTER TABLE users ALTER COLUMN users_password TYPE varchar(100);

CREATE TABLE EVENT_BLOCKED_USER(
                           BLOCKED_ID NUMERIC(10,0),
                           USERS_BLOCKED_ID NUMERIC(10,0) ,
                           USERS_ID NUMERIC(10,0) ,
                           CONSTRAINT FK_B_USERS_ID FOREIGN KEY(USERS_ID)
                               REFERENCES USERS (USERS_ID)
);
COMMENT ON COLUMN EVENT_BLOCKED_USER.BLOCKED_ID IS 'Unique ID Blocked';
COMMENT ON COLUMN EVENT_BLOCKED_USER.USERS_BLOCKED_ID IS 'ID Blocked User';
COMMENT ON COLUMN EVENT_BLOCKED_USER.USERS_ID IS 'FK KEY to USERS';