CREATE TABLE CATEGORY(
CATEGORY_ID Numeric(10,0)  CONSTRAINT NN_CATEGORY_ID NOT NULL,
CATEGORY_NAME VARCHAR(50) CONSTRAINT NN_CATEGORY_NAME NOT NULL,
CONSTRAINT CATEGORY_PK PRIMARY KEY(CATEGORY_ID)
);
COMMENT ON COLUMN CATEGORY.CATEGORY_ID IS 'Unique ID Category';
COMMENT ON COLUMN CATEGORY.CATEGORY_NAME IS 'Name Category';