CREATE TABLE EVENT_USER(
EVENT_ID NUMERIC(10,0) ,
USERS_ID NUMERIC(10,0) ,
CONSTRAINT EVENT_USER_PK PRIMARY KEY(EVENT_ID,USERS_ID),
CONSTRAINT FK_EVENT_ID FOREIGN KEY(EVENT_ID)
REFERENCES EVENTS (EVENTS_ID),
CONSTRAINT FK_USERS_ID FOREIGN KEY(USERS_ID)
REFERENCES USERS (USERS_ID)
);
COMMENT ON COLUMN EVENT_USER.EVENT_ID IS 'FK key to EVENT';
COMMENT ON COLUMN EVENT_USER.USERS_ID IS 'FK KEY to USERS';